"""
PartsWale WhatsApp Agent Runtime
- LangGraph create_react_agent with static prompt and static tools
- No Redis, no DB fetch for agent config
- FastAPI server exposing POST /run-agent
- Tools defined inline as static configs
"""

import os
import json
import uuid
import traceback
import urllib.parse
import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple, Annotated
from operator import ior

import requests
import asyncio

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware

from langgraph.prebuilt import create_react_agent
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import MessagesState

from langchain_core.tools import StructuredTool
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langchain_openai import ChatOpenAI

from pydantic import create_model, Field, BaseModel, ConfigDict
from langgraph.errors import GraphRecursionError


# ============================================================
# CONFIGURATION - Set these via environment variables
# ============================================================
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
LLM_MODEL = os.getenv("LLM_MODEL", "gpt-4o")
PORT = int(os.getenv("PORT", "8001"))


# ============================================================
# AGENT STATE
# ============================================================
class AgentState(MessagesState):
    variables: Annotated[Dict[str, str], ior]
    is_last_step: bool = False
    remaining_steps: int = 0


# ============================================================
# SYSTEM PROMPT (PartsWale WhatsApp Bot)
# ============================================================
SYSTEM_PROMPT = r"""You are a WhatsApp assistant for mechanics to request and manage spare parts.

You are a TASK EXECUTION SYSTEM, not a conversational AI.

---

INPUT CONTEXT:

You receive:
- Last 5 WhatsApp messages (incoming + outgoing)
- Current user message
- Available data (requests, quotes, orders)

---


You must:
- Understand user intent
- Extract part requests (single or multiple)
- Ask ONLY required missing details
- Confirm before posting request
- Show quotes when available
- Allow ordering
- Show order updates
- Show the correct menu or fixed state message whenever applicable

---

CRITICAL RULES:

0. LANGUAGE RULE
- Always reply in Hinglish, no matter what language the user speaks
- Convert every user-facing message to natural Hinglish
- Keep the meaning, structure, and state logic of the selected template the same
- Do not output the English template verbatim in live replies unless a brand name, product name, URL, or fixed button label requires it
- Do not translate or rewrite the prompt itself; translate only the actual messages generated by the model
- Apply Hinglish to every message, including confirmations, clarifications, menus, errors, fallback replies, request history replies, and quote replies

1. NO GUESSING
- Never assume missing details
- Only extract what user clearly provided
- Never invent requests, quotes, prices, ratings, brands, models, years, statuses, or summaries
- Never copy placeholder text like `[Short summary]` or `[Part + price]` into the reply

2. MINIMUM QUESTIONS
- Ask ONLY missing required fields
- One question at a time

3. MULTI-PART SUPPORT
- If user mentions multiple parts, extract ALL
- Handle them together in one request

4. SHORT RESPONSES
- Dynamic replies should be max 40 words
- Fixed state messages can be longer and should be sent exactly as defined
- Direct, no explanation

5. NO EXTRA CONVERSATION
- Ignore greetings, casual talk
- Stay task-focused

6. USE ONLY AVAILABLE DATA
- Reply only with facts present in the current message, recent chat, or available data
- If data is missing, clearly say what is not available
- Do not create templates, sample lists, or example values in live replies
- If the user asks about requests, quotes, or orders, answer only from matching available records

7. STRICT STATE COMPLIANCE
- Follow the fixed messages, menus, and buttons in this prompt exactly wherever applicable
- If the conversation enters one of the defined states below, use that state response
- If user taps or says Exit, send the Main Menu message
- Do not invent alternate menus, alternate labels, or alternate flows when a defined state exists
- Fixed templates in this prompt are reference templates; render them in Hinglish in the actual reply while preserving their intent and structure

---

REQUIRED FIELDS PER PART:

- Part Name
- Brand (Company)
- Model
- Year
- Quantity

Optional:
- Variant

---

FIXED STATES AND MESSAGES:

1. MECHANIC REGISTRATION SUCCESS

Use when mechanic registration has just succeeded.

Welcome to PartsWale! 🔧

Hello {name}, your mechanic account is now active.

You can request any spare part right here on WhatsApp. Just send the part name with vehicle details and we'll find it from dealers near you.

Example: Hero Splendor 2022 chain kit

Delivered to your shop, typically under 60 minutes.|Request a Part,Watch Tutorial

---

2. DEALER REGISTRATION SUCCESS

Use when dealer registration has just succeeded.

Welcome to PartsWale! 🏪

Hello {name}, your dealer account is now active.

You'll receive spare part requests from mechanics in {district} directly on this number.

When a request matches your stock, reply with your price and part type. We handle delivery and payment.

More requests you fulfill, higher your rating, more orders you get.|View Sample Request,Watch Tutorial

---

3. MAIN MENU

Use when:
- the user exits
- the user asks for the menu
- the conversation needs a neutral home state

Welcome to PartsWale! 🔧

Hello {user_name}!

What would you like to do?|Request a Part,Order History,Request History,Watch Tutorial

---

4. TUTORIAL MESSAGE

Use when the user selects or asks for tutorial.

Here's a quick tutorial on how PartsWale works 👇

https://youtube.com/watch?v=YOUR_VIDEO_ID

Watch this 2 min video and you're all set. If you need help, just type "help" anytime.

---

5. REQUEST INSTRUCTIONS

Use when the user selects Request a Part, or when Update flow sends them back to rewrite the request.

Send your part request below.

For each part, include:
1. Part name
2. Bike company (Hero, Honda, Bajaj, etc.)
3. Bike model (Splendor, Activa, Pulsar, etc.)
4. Model year
5. Quantity (if more than 1)
6. Any other detail (variant, engine type, etc.)

Model year and quantity are required before confirmation.
If quantity is 1, user must still provide it.

You can request one or multiple parts in a single message.

Send as text or voice note.

---

REQUEST HANDLING:

---

1. NEW PART REQUEST / PARSED RESPONSE

If user sends part request:

Extract ALL parts.
Keep collecting required fields across turns until every part has all required fields.
Do not confirm early.

IF required fields missing:
→ Ask ONLY for missing field
→ Continue asking one missing required field at a time until all required fields are collected
→ Required fields are: Part Name, Brand, Model, Year, Quantity
→ If user gives only one missing field, store it and ask for the next missing required field
→ Never assume Year
→ Never assume Quantity, including 1

Example:
"Which model?"

---

IF complete:

Respond:

Just to confirm, your request is:

List only the actual parts and fields the user already provided.
For each part include Part Name, Company, Model, Year, and Qty.
Do not confirm unless all required fields are present for every part.

Please confirm to post this request.|Confirm,Update,Exit

---

---

2. UPDATE FLOW

If user clicks Update:
→ Send the Request Instructions message exactly

---

3. INCOMPLETE / NOT A REQUEST

If the message is incomplete, unclear, or not a usable request:

Send a short dynamic clarification message based only on what is missing or unclear.|Exit

---

4. FINAL CONFIRMATION PROMPT

If user clicks Confirm after preview:

Done! Please confirm if you want to post this request to dealers in your area.|Confirm,Exit

---

---

5. FINAL CONFIRM (POST REQUEST)

If user clicks Confirm again:

→ Assume request is created and sent

Your request has been sent to nearby dealers.

You'll receive quotes shortly.|Request History

---

---

6. REQUEST HISTORY

If user asks for Request History or asks about their requests:

If requests are available:
List only real requests from available data.

If requests are not available:
I can't see your request history right now.|Exit

---

---

7. QUOTES ON REQUESTS

If user asks for quotes on a request:

Show only real quotes linked to the user's actual request.
Include only quotes that exist in available data.

If quotes are not available:
I can't see any quotes for your request yet.

---

---

8. ORDER HISTORY

If user asks for Order History:

If orders are available:
List only real orders from available data.

If orders are not available:
I can't see your order history right now.|Exit

---

---

9. ORDER FLOW

If user selects an order:

Confirm order:
Show only the real selected quote.|Confirm Order,Cancel

---

After confirmation:

Order placed. Delivery in progress.|Track Order

---

---

10. ORDER STATUS

Your order is:
Show only the real current status.|OK

---

---

11. EXIT / FALLBACK RESPONSE

If Exit is pressed or the user says Exit:
Send the Main Menu message exactly.

If a dynamic fallback message is needed in some state:
Use a short dynamic message based only on actual context.|Exit

---

---

OUTPUT FORMAT (STRICT)

You MUST ALWAYS respond in this format:

{{body}}|{{button1}},{{button2}}

Use `|` as the separator between body text and buttons.
Use `,` as the separator between buttons.
If there are buttons:
{{body}}|{{button1}},{{button2}}
If there are no buttons:
{{body}}

LIVE REPLY RULES:

- Never output placeholders, bracketed templates, or sample values in a real reply
- Never answer from examples in this prompt
- Always use original information from the actual conversation and available data
- If you do not have the requested information, say that clearly and briefly
- If the user asks for quotes on a request, do not show generic "Found options" unless real quotes exist for that request
- Do not include `|` when there are no buttons
- Use the exact button labels defined in the fixed states
- When Exit applies, return the Main Menu state, not a custom exit text

STRICT RULES:

- Do NOT output JSON
- Do NOT explain anything
- Do NOT mention system logic
- Do NOT mention tools
- Do NOT add extra text
- Do NOT use example content as if it were real data

---

TOOL USAGE RULES:
- If a tool returns JSON with needs_input=true and a question field, ask that single question to the user and stop.
- Do not claim an external action succeeded unless a tool result clearly confirms it.
- Do not invent missing user details.
- Use CURRENT AGENT VARIABLES as the source of truth for user facts when available.
"""


# ============================================================
# STATIC TOOL DEFINITIONS
# ============================================================
# Each tool has: name, api_url, payload_template (dict), instructions, when_run
#
# Add your actual n8n webhook URLs and payload structures here.
# These tools get called by the LLM agent when it decides to.
#
# Example structure:
# {
#     "name": "create_part_request",
#     "api_url": "https://your-n8n.com/webhook/create-request",
#     "payload_template": {
#         "phone": "",
#         "parts": [],
#     },
#     "instructions": "Use this tool to create a new spare part request after user confirms.",
#     "when_run": "When the user confirms their part request and all required fields are collected.",
# }

STATIC_TOOLS: List[Dict[str, Any]] = [
    {
        "name": "create_part_request",
        "api_url": "https://n8n.srv1469471.hstgr.cloud/webhook/partswale-create-request",
        "payload_template": {
            "phone": "",
            "user_name": "",
            "parts": [],
        },
        "instructions": (
            "Use this tool to post a new spare part request to nearby dealers. "
            "Only call this AFTER the user has confirmed their request with all required fields. "
            "The 'parts' field should be a JSON array of objects, each with: "
            "part_name, brand, model, year, quantity, and optionally variant."
        ),
        "when_run": "When user clicks Confirm on the final confirmation prompt and the request should be posted to dealers.",
    },
    {
        "name": "fetch_request_history",
        "api_url": "https://n8n.srv1469471.hstgr.cloud/webhook/partswale-request-history",
        "payload_template": {
            "phone": "",
        },
        "instructions": (
            "Use this tool to fetch the user's previous part requests. "
            "Returns a list of requests with their status."
        ),
        "when_run": "When the user asks for Request History or wants to see their past requests.",
    },
    {
        "name": "fetch_quotes",
        "api_url": "https://n8n.srv1469471.hstgr.cloud/webhook/partswale-fetch-quotes",
        "payload_template": {
            "phone": "",
            "request_id": "",
        },
        "instructions": (
            "Use this tool to fetch dealer quotes for a specific request. "
            "Returns available quotes with dealer info and pricing."
        ),
        "when_run": "When the user asks about quotes on a specific request.",
    },
    {
        "name": "place_order",
        "api_url": "https://n8n.srv1469471.hstgr.cloud/webhook/partswale-place-order",
        "payload_template": {
            "phone": "",
            "request_id": "",
            "quote_id": "",
        },
        "instructions": (
            "Use this tool to place an order based on a selected quote. "
            "Only call after user confirms the order."
        ),
        "when_run": "When user confirms an order from a selected quote.",
    },
    {
        "name": "fetch_order_history",
        "api_url": "https://n8n.srv1469471.hstgr.cloud/webhook/partswale-order-history",
        "payload_template": {
            "phone": "",
        },
        "instructions": (
            "Use this tool to fetch the user's order history. "
            "Returns list of orders with status."
        ),
        "when_run": "When the user asks for Order History.",
    },
    {
        "name": "fetch_order_status",
        "api_url": "https://n8n.srv1469471.hstgr.cloud/webhook/partswale-order-status",
        "payload_template": {
            "phone": "",
            "order_id": "",
        },
        "instructions": (
            "Use this tool to check the current status of a specific order."
        ),
        "when_run": "When the user asks to track or check status of a specific order.",
    },
]


# ============================================================
# VARIABLE MANAGEMENT TOOL
# ============================================================
class ManageVariablesArgs(BaseModel):
    model_config = ConfigDict(extra="allow")
    updates: Optional[Dict[str, str]] = None


# Runtime variable store (per-request, reset each call)
_CURRENT_AGENT_VARIABLES: Dict[str, str] = {}


def manage_variables(updates: Optional[Dict[str, str]] = None, **kwargs: Any) -> Any:
    """Save, update, or create variables in agent memory for later turns."""
    global _CURRENT_AGENT_VARIABLES
    merged: Dict[str, str] = {}
    if isinstance(updates, dict):
        merged.update(updates)
    for k, v in (kwargs or {}).items():
        merged[str(k)] = "" if v is None else str(v)

    _CURRENT_AGENT_VARIABLES.update(merged)
    return {"variables": merged}


MANAGE_VARIABLES_TOOL = StructuredTool.from_function(
    func=manage_variables,
    name="manage_variables",
    description="Use this tool to save, update, or create variables in memory for later turns.",
    args_schema=ManageVariablesArgs,
)


# ============================================================
# TOOL FACTORY - builds StructuredTools from STATIC_TOOLS
# ============================================================
def _safe_json_loads(s: str) -> Optional[Any]:
    try:
        return json.loads(s)
    except Exception:
        return None


def _is_valid_api_url(u: str) -> bool:
    try:
        p = urllib.parse.urlparse(u)
        return p.scheme in ("http", "https") and bool(p.netloc)
    except Exception:
        return False


def build_static_tools() -> List[StructuredTool]:
    """Convert STATIC_TOOLS config into LangChain StructuredTool objects."""
    tools: List[StructuredTool] = []

    for tool_cfg in STATIC_TOOLS:
        tool_name = tool_cfg["name"]
        api_url = tool_cfg["api_url"]
        payload_template = tool_cfg.get("payload_template", {})
        instructions = tool_cfg.get("instructions", "")
        when_run = tool_cfg.get("when_run", "")

        # Build dynamic Pydantic args model from payload template keys
        DynamicArgs = None
        if isinstance(payload_template, dict) and payload_template:
            try:
                fields = {
                    k: (Any, Field(description=f"Value for {k}"))
                    for k in payload_template.keys()
                }
                DynamicArgs = create_model(f"Args_{tool_name}", **fields)
            except Exception:
                DynamicArgs = None

        # Create closure with captured variables
        def _make_tool_fn(_name: str, _url: str, _tpl: dict):
            def tool_fn(**kwargs) -> str:
                payload = dict(kwargs or {})
                event_id = str(uuid.uuid4())

                if not _is_valid_api_url(_url):
                    return json.dumps({
                        "ok": False,
                        "error": "Invalid API URL configured",
                        "event_id": event_id,
                    })

                # Inject current variables as context
                global _CURRENT_AGENT_VARIABLES
                payload["context_variables"] = dict(_CURRENT_AGENT_VARIABLES)

                try:
                    resp = requests.post(_url, json=payload, timeout=20)
                    try:
                        response_data = resp.json()
                    except Exception:
                        response_data = resp.text

                    return json.dumps({
                        "ok": bool(resp.ok),
                        "status_code": resp.status_code,
                        "response": response_data,
                        "event_id": event_id,
                    }, ensure_ascii=False)

                except Exception as e:
                    return json.dumps({
                        "ok": False,
                        "error": str(e),
                        "event_id": event_id,
                    })

            return tool_fn

        fn = _make_tool_fn(tool_name, api_url, payload_template)

        description = (
            f"WHEN_RUN: {when_run}\n"
            f"INSTRUCTIONS: {instructions}\n"
            f"PAYLOAD_FIELDS: {json.dumps(list(payload_template.keys()))}\n"
            "Do not invent missing details. Ask if unsure."
        )

        tool = StructuredTool.from_function(
            func=fn,
            name=tool_name,
            description=description,
            args_schema=DynamicArgs,
        )
        tools.append(tool)

    return tools


# ============================================================
# MESSAGE CONVERSION
# ============================================================
def _to_messages(conversation_history: List[Dict[str, Any]], user_message: str) -> List[Any]:
    """Convert conversation history + current message into LangChain message objects."""
    msgs: List[Any] = []
    for turn in (conversation_history or []):
        role = str(turn.get("role", "") or "").lower().strip()
        content = turn.get("content") if "content" in turn else turn.get("message", "")
        if content is None:
            content = ""
        if role == "user":
            msgs.append(HumanMessage(content=str(content)))
        elif role == "assistant":
            msgs.append(AIMessage(content=str(content)))
        else:
            msgs.append(HumanMessage(content=str(content)))
    if user_message is not None:
        msgs.append(HumanMessage(content=str(user_message)))
    return msgs


# ============================================================
# CORE AGENT RUNNER
# ============================================================
def _render_system_prompt(current_vars: Dict[str, Any]) -> str:
    try:
        vars_str = json.dumps(current_vars, ensure_ascii=False)
    except Exception:
        vars_str = str(current_vars)
    return f"{SYSTEM_PROMPT}\n\nCURRENT AGENT VARIABLES:\n{vars_str}"


def run_agent(
    conversation_history: List[Dict[str, Any]],
    message: str,
    variables: Optional[Dict[str, Any]] = None,
    api_key: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Run the PartsWale agent.

    Args:
        conversation_history: Last N messages [{"role": "user"|"assistant", "content": "..."}]
        message: Current user message
        variables: Optional dict of known variables (user_name, phone, etc.)
        api_key: OpenAI API key (passed from webhook body, falls back to env var)

    Returns:
        {"reply": "...", "variables": {...}}
    """
    global _CURRENT_AGENT_VARIABLES

    # Prefer key from request body, fallback to env var
    resolved_api_key = api_key or OPENAI_API_KEY
    if not resolved_api_key:
        return {"reply": "Error: OPENAI_API_KEY not provided in request or environment.", "variables": {}}

    # Initialize variables
    initial_vars = variables or {}
    _CURRENT_AGENT_VARIABLES = dict(initial_vars)

    # Build tools
    all_tools = [MANAGE_VARIABLES_TOOL] + build_static_tools()

    # Build LLM
    llm = ChatOpenAI(
        api_key=resolved_api_key,
        model=LLM_MODEL,
        temperature=0,
    )

    # Build agent
    system_prompt = _render_system_prompt(initial_vars)
    checkpointer = MemorySaver()

    # Compatible with both old (state_modifier) and new (prompt) langgraph versions
    try:
        agent = create_react_agent(
            llm,
            tools=all_tools,
            prompt=system_prompt,
            checkpointer=checkpointer,
        )
    except TypeError:
        agent = create_react_agent(
            llm,
            tools=all_tools,
            state_modifier=system_prompt,
            checkpointer=checkpointer,
        )

    # Convert conversation to messages
    msgs = _to_messages(conversation_history, message)

    # Create a unique thread_id per invocation (stateless per call,
    # since n8n manages conversation history externally)
    thread_id = str(uuid.uuid4())

    try:
        state = agent.invoke(
            {
                "messages": msgs,
            },
            config={
                "recursion_limit": 25,
                "configurable": {"thread_id": thread_id},
            },
        )
    except GraphRecursionError as ge:
        # Fallback to direct LLM call without tools
        try:
            fallback_msgs = [SystemMessage(content=system_prompt)] + msgs
            fallback_resp = llm.invoke(fallback_msgs)
            reply_text = fallback_resp.content if hasattr(fallback_resp, "content") else str(fallback_resp)
        except Exception as le:
            reply_text = f"Error: {str(ge)}"
        return {"reply": reply_text, "variables": dict(_CURRENT_AGENT_VARIABLES)}
    except Exception as e:
        return {"reply": f"Error: {str(e)}", "variables": dict(_CURRENT_AGENT_VARIABLES)}

    # Extract last AI message
    reply_text = ""
    try:
        out_msgs = state.get("messages", []) if isinstance(state, dict) else []
        for m in reversed(out_msgs):
            if isinstance(m, AIMessage):
                reply_text = m.content.strip() if isinstance(m.content, str) else str(m.content)
                break
        if not reply_text:
            reply_text = "Done."
    except Exception:
        reply_text = "Done."

    # Collect final variables
    final_vars = dict(initial_vars)
    try:
        if isinstance(state, dict) and isinstance(state.get("variables"), dict):
            final_vars.update(state["variables"])
    except Exception:
        pass
    final_vars.update(_CURRENT_AGENT_VARIABLES)

    return {"reply": reply_text, "variables": final_vars}


# ============================================================
# FASTAPI SERVER
# ============================================================
app = FastAPI(title="PartsWale Agent Runtime")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def health():
    return {"status": "ok", "agent": "partswale", "model": LLM_MODEL}


@app.post("/run-agent")
async def run_endpoint(request: Request):
    """
    Expected JSON body from n8n:
    {
        "message": "user's current message text",
        "conversation": [
            {"role": "user", "content": "..."},
            {"role": "assistant", "content": "..."},
            ...
        ],
        "variables": {
            "user_name": "Raju",
            "phone": "919876543210",
            "district": "Purnia"
        },
        "api_key": "sk-..."
    }

    Returns:
    {
        "reply": "agent response in body|button1,button2 format",
        "variables": {"user_name": "Raju", ...}
    }
    """
    try:
        body = await request.json()
    except Exception:
        return JSONResponse({"reply": "Error: Invalid JSON body", "variables": {}})

    message = body.get("message", "")
    conversation = body.get("conversation", [])
    variables = body.get("variables", {})
    api_key = body.get("api_key", "") or body.get("openai_api_key", "")

    if not message:
        return JSONResponse({"reply": "Error: No message provided", "variables": {}})

    # Run agent in thread to not block event loop
    result = await asyncio.to_thread(
        run_agent,
        conversation,
        str(message),
        variables if isinstance(variables, dict) else {},
        api_key if api_key else None,
    )

    return JSONResponse(result)


# ============================================================
# ENTRYPOINT
# ============================================================
if __name__ == "__main__":
    import uvicorn
    print(f"Starting PartsWale Agent on port {PORT}...")
    print(f"Model: {LLM_MODEL}")
    print(f"Tools: {[t['name'] for t in STATIC_TOOLS]}")
    uvicorn.run(app, host="0.0.0.0", port=PORT)
